package co.edu.cue.cue_swap.domain.enums;

public enum Career {
    INGENIERIA_DE_SOFTWARE,
    INGENIERIA_INDUSTRIAL,
    INGENIERIA_CIVIL,
    ADMINISTRACION_DE_EMPRESAS,
    MEDICINA,
    ENFERMERIA,
    PSICOLOGIA,
    MEDICINA_VERTERINARIA,
    MARKETING_DIGITAL
}
